import { Injectable } from '@angular/core'
import { InMemoryDbService } from 'angular-in-memory-web-api'

@Injectable({
  providedIn: 'root',
})
export class InMemoryApiService implements InMemoryDbService {
  constructor() {}

  createDb() {
    let employeesList = [
      {
        id:1,
        employeeId: 'admin',
        password: 'Admin123!',
        employeeName: 'AdminUser',
      },
      {
        id:2,
        employeeId: 'FHA1001',
        password: 'Abc@12345',
        employeeName: 'TestUser1'
      }     
    ]
    let flights = [
      {
        id: 1,
        ToFlight: 'London',
        FromFlight: 'Bhubaneswar',
        BoardingStatus: 'Scheduled',
      },
      {
        id: 2,
        ToFlight: 'New York',
        FromFlight: 'Bhubaneswar',
        BoardingStatus: 'Scheduled',
      },
      {
        id: 3,
        ToFlight: 'Seoul',
        FromFlight: 'Bhubaneswar',
        BoardingStatus: 'Scheduled',
      },
      {
        id: 4,
        ToFlight: 'Honk Kong',
        FromFlight: 'Bhubaneswar',
        BoardingStatus: 'Scheduled',
      },
    ]
    let Londonpassengers = [
      {
        id: 1,
        pId: 1,
        seatNo: 21,
        name: ' Rajesh Arora',
        address: '91,Sahid Nagar Bhubaneswar',
        passport: 'true',
        checkedInStatus: 'N/A',
        infants: 0,
        wheelChair: 'true',
        mealsOpted: 'true',
        services: ['Wi-Fi'],
      },
      {
        id: 2,
        pId: 2,
        seatNo: 22,
        name: ' Sulgana Priya',
        address: 'Plot No.-231, Kanan Vihar Bhubaneswar',
        passport: 'true',
        checkedInStatus: 'N/A',
        infants: 0,
        wheelChair: 'true',
        mealsOpted: 'true',
        services: ['Entertainment'],
      },
      {
        id: 4,
        pId: 4,
        seatNo: 23,
        name: 'Nitya Menon',
        address: '1/77, IRC Village, Bhuabaneswar',
        passport: 'true',
        checkedInStatus: 'Checked In',
        infants: 0,
        wheelChair: 'true',
        mealsOpted: 'true',
        services: ['Wi-Fi'],
      },
      {
        id: 5,
        pId: 5,
        seatNo: 24,
        name: 'Arya Khana',
        address: 'GA 203, New town Village, Bhuabaneswar',
        passport: 'true',
        checkedInStatus: 'Checked In',
        infants: 0,
        wheelChair: 'true',
        mealsOpted: 'true',
        services: ['Wi-Fi'],
      },
      {
        id: 6,
        pId: 6,
        seatNo: 25,
        name: 'Vidya Shekhar',
        address: 'Plot No. 256, Kalarahanga, Bhuabaneswar',
        passport: 'true',
        checkedInStatus: 'Checked In',
        infants: 0,
        wheelChair: 'true',
        mealsOpted: 'true',
        services: ['Wi-Fi'],
      },
      {
        id: 3,
        pId: 3,
        seatNo: 26,
        name: 'Priyanka Chopra',
        address: '190/2, Nayapalli, Bhuabaneswar',
        passport: 'true',
        checkedInStatus: 'N/A',
        infants: 0,
        wheelChair: 'true',
        mealsOpted: 'true',
        services: ['Wi-Fi'],
      },
    ]
    let NewYorkPassengers = [
      {
        id: 1,
        pId: 1,
        seatNo: 21,
        name: 'Swetalaya Murkharjee',
        address: '23/6 MG Road BJB College Bhubaneswar',
        passport: 'true',
        checkedInStatus: 'N/A',
        infants: 0,
        wheelChair: 'true',
        mealsOpted: 'true',
        services: ['Entertainment'],
      },
      {
        id: 2,
        pId: 2,
        seatNo: 31,
        name: 'Aradhaya Kailash',
        address: 'HIG-221, Sailashree Vihar Bhubaneswar',
        passport: 'true',
        checkedInStatus: 'Checked In',
        infants: 0,
        wheelChair: 'true',
        mealsOpted: 'true',
        services: ['Wi-Fi'],
      },
      {
        id: 3,
        pId: 3,
        seatNo: 31,
        name: 'Aradhaya Kailash',
        address: 'HIG-221, Sailashree Vihar Bhubaneswar',
        passport: 'true',
        checkedInStatus: 'Checked In',
        infants: 0,
        wheelChair: 'true',
        mealsOpted: 'true',
        services: ['Wi-Fi'],
      },
      {
        id: 4,
        pId: 4,
        seatNo: 31,
        name: 'Aradhaya Kailash',
        address: 'HIG-221, Sailashree Vihar Bhubaneswar',
        passport: 'true',
        checkedInStatus: 'Checked In',
        infants: 0,
        wheelChair: 'true',
        mealsOpted: 'true',
        services: ['Wi-Fi'],
      },
      {
        id: 5,
        pId: 5,
        seatNo: 31,
        name: 'Aradhaya Kailash',
        address: 'HIG-221, Sailashree Vihar Bhubaneswar',
        passport: 'true',
        checkedInStatus: 'Checked In',
        infants: 0,
        wheelChair: 'true',
        mealsOpted: 'true',
        services: ['Wi-Fi'],
      },

      {
        id: 6,
        pId: 6,
        seatNo: 31,
        name: 'Aradhaya Kailash',
        address: 'HIG-221, Sailashree Vihar Bhubaneswar',
        passport: 'true',
        checkedInStatus: 'Checked In',
        infants: 0,
        wheelChair: 'true',
        mealsOpted: 'true',
        services: ['Wi-Fi'],
      }
    ]
    let SeoulPassengers = [
      {
        id: 1,
        pId: 1,
        seatNo: 53,
        name: 'Sourav Senapati',
        address: '261/1 Spring Leaf Apartment Bhubaneswar',
        passport: 'true',
        checkedInStatus: 'N/A',
        infants: 0,
        wheelChair: 'true',
        mealsOpted: 'true',
        services: ['Entertainment,Wi-Fi'],
      },
      {
        id: 2,
        pId: 2,
        seatNo: 33,
        name: 'Amulya Jena',
        address: 'S3-202, Nialdrivihar Bhubaneswar',
        passport: 'true',
        checkedInStatus: 'Checked In',
        infants: 0,
        wheelChair: 'true',
        mealsOpted: 'true',
        services: ['Wi-Fi'],
      },
      {
        id: 3,
        pId: 3,
        seatNo: 33,
        name: 'Akash Sathpathy',
        address: 'Plot No-440, Lumbinivihar Bhubaneswar',
        passport: 'true',
        checkedInStatus: 'Checked In',
        infants: 0,
        wheelChair: 'true',
        mealsOpted: 'true',
        services: ['Wi-Fi'],
      },
      {
        id: 4,
        pId: 4,
        seatNo: 33,
        name: 'Akshay Mohantu',
        address: 'S3-1/78, Nialdrivihar Bhubaneswar',
        passport: 'true',
        checkedInStatus: 'N/A',
        infants: 0,
        wheelChair: 'true',
        mealsOpted: 'true',
        services: ['Wi-Fi'],
      },
    ]
    let HongKongPassengers = [
      {
        id: 1,
        pId: 1,
        seatNo: 81,
        name: 'Nitya Reddy',
        address: '231/6 College Road Bhubaneswar',
        passport: 'true',
        checkedInStatus: 'N/A',
        infants: 0,
        wheelChair: 'true',
        mealsOpted: 'true',
        services: ['Entertainment'],
      },
      {
        id: 2,
        pId: 2,
        seatNo: 61,
        name: 'Pihu Kulkarni',
        address: 'HIG-21, Sailashree Vihar Bhubaneswar',
        passport: 'true',
        checkedInStatus: 'Checked In',
        infants: 0,
        wheelChair: 'true',
        mealsOpted: 'true',
        services: ['Wi-Fi'],
      },
      {
        id: 3,
        pId: 3,
        seatNo: 61,
        name: 'Pihu Kulkarni',
        address: 'HIG-21, Sailashree Vihar Bhubaneswar',
        passport: 'true',
        checkedInStatus: 'Checked In',
        infants: 0,
        wheelChair: 'true',
        mealsOpted: 'true',
        services: ['Wi-Fi'],
      },
      {
        id: 4,
        pId: 4,
        seatNo: 61,
        name: 'Pihu Kulkarni',
        address: 'HIG-21, Sailashree Vihar Bhubaneswar',
        passport: 'true',
        checkedInStatus: 'Checked In',
        infants: 0,
        wheelChair: 'true',
        mealsOpted: 'true',
        services: ['Wi-Fi'],
      },
    ]
    return { employeesList, flights, Londonpassengers, NewYorkPassengers,SeoulPassengers,HongKongPassengers }
  }
}
